package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n<title>VietNamNEWS</title>\r\n<meta charset=\"utf-8\">\r\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n<link rel=\"icon\" href=\"images/favorite-icon.png\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/bootstrap.min.css\">\r\n<link href=\"https://fonts.googleapis.com/css?family=Nunito&amp;subset=vietnamese\" rel=\"stylesheet\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/font-awesome.min.css\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/animate.css\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/slick.css\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/theme.css\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/custom.css\">\r\n<!--[if lt IE 9]>\r\n<script src=\"assets/js/html5shiv.min.js\"></script>\r\n<script src=\"assets/js/respond.min.js\"></script>\r\n<![endif]-->\r\n</head>\r\n<body>\r\n<div id=\"preloader\">\r\n");
      out.write("  <div id=\"status\">&nbsp;</div>\r\n</div>\r\n<a class=\"scrollToTop\" href=\"#\"><span></span></a>\r\n<div class=\"container\">\r\n  <header id=\"header\">\r\n    <div class=\"row\">\r\n      <div class=\"col-lg-12 col-md-12\">\r\n        <div class=\"header_top\">\r\n          <div class=\"header_top_left\">\r\n            <ul class=\"top_nav\">\r\n              <li><a href=\"index.html\">Trang chủ</a></li>\r\n              <li><a href=\"pages/page.html\">Giới thiệu</a></li>\r\n              <li><a href=\"pages/contact.html\">Liên hệ</a></li>\r\n              <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#modalSignIn\">Đăng nhập</a></li>\r\n              <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#modalSignUp\">Đăng ký</a></li>\r\n              <!-- <li><a href=\"index.html\"><img src=\"images/favorite-icon.png\"></a></li> -->\r\n            </ul>\r\n          </div>\r\n          <div class=\"header_top_right\">\r\n            <form action=\"#\" class=\"search_form\">\r\n              <input type=\"text\" placeholder=\"Tìm kiếm\">\r\n              <input type=\"submit\" value=\"\">\r\n            </form>\r\n");
      out.write("          </div>\r\n        </div>\r\n        <div class=\"header_bottom\">\r\n          <div class=\"header_bottom_left\">\r\n            <a class=\"logo\" href=\"index.html\">Việt Nam <strong>NEWS</strong> <span>Nắm bắt thời cuộc</span></a>\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </div>\r\n  </header>\r\n  <div id=\"navarea\">\r\n    <nav class=\"navbar navbar-default\" role=\"navigation\">\r\n      <div class=\"container-fluid\">\r\n        <div class=\"navbar-header\">\r\n          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\"> <span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\r\n        </div>\r\n        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n          <ul class=\"nav navbar-nav custom_nav\">\r\n            <li class=\"\"><a href=\"index.html\">Trang chủ</a></li>\r\n            <li class=\"\"><a href=\"pages/archive-main.html\">Thời sự</a></li>\r\n");
      out.write("            <li class=\"\"><a href=\"pages/archive-main.html\">Thể thao</a></li>\r\n            <li class=\"\"><a href=\"pages/archive-main.html\">Kinh tế</a></li>\r\n            <li class=\"\"><a href=\"pages/archive-main.html\">Giải trí</a></li>\r\n            <li class=\"\"><a href=\"pages/archive-main.html\">Sức khoẻ</a></li>\r\n            <li class=\"\"><a href=\"pages/archive-main.html\">Pháp luật</a></li>\r\n            <li class=\"\"><a href=\"pages/archive-main.html\">Giáo dục</a></li>\r\n            <li class=\"\"><a href=\"pages/archive-main.html\">Khoa học</a></li>\r\n            <li class=\"\"><a href=\"pages/archive-main.html\">Du lịch</a></li>\r\n            <li class=\"\"><a href=\"pages/archive-main.html\">Thế giới</a></li>\r\n            <!-- <li class=\"dropdown\"> <a href=\"#\" class=\"\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">Archives</a>\r\n              <ul class=\"dropdown-menu\" role=\"menu\">\r\n                <li><a href=\"pages/archive-main.html\">Thể thao</a></li>\r\n                <li><a href=\"pages/archive1.html\">Bóng đá</a></li>\r\n");
      out.write("                <li><a href=\"pages/archive2.html\">Bóng bàn</a></li>\r\n                <li><a href=\"pages/archive3.html\">Thể thao điện tử 3</a></li>\r\n              </ul>\r\n            </li> -->\r\n            <!-- <li><a href=\"pages/single.html\">Single page</a></li>\r\n            <li><a href=\"pages/contact.html\">Contact</a></li>\r\n            <li><a href=\"pages/404.html\">404 page</a></li> -->\r\n          </ul>\r\n        </div>\r\n      </div>\r\n    </nav>\r\n  </div>\r\n  <section id=\"mainContent\">\r\n    <!-- <div class=\"content_top\">\r\n      <div class=\"row\">\r\n        <div class=\"col-lg-6 col-md-6 col-sm6\">\r\n          <div class=\"latest_slider\">\r\n            <div class=\"slick_slider\">\r\n              <div class=\"single_iteam\"><img src=\"images/xalattop.jpg\" alt=\"\">\r\n                <h2><a class=\"slider_tittle\" href=\"pages/single.html\">Đường 5.000 tỷ nối bốn quận, huyện Hà Nội sắp khánh thành</a></h2>\r\n              </div>\r\n              <div class=\"single_iteam\"><img src=\"images/550x330x2.jpg\" alt=\"\">\r\n                <h2><a class=\"slider_tittle\" href=\"pages/single.html\">Fusce eu nulla semper porttitor felis sit amet</a></h2>\r\n");
      out.write("              </div>\r\n              <div class=\"single_iteam\"><img src=\"images/550x330x3.jpg\" alt=\"\">\r\n                <h2><a class=\"slider_tittle\" href=\"pages/single.html\">Fusce eu nulla semper porttitor felis sit amet</a></h2>\r\n              </div>\r\n              <div class=\"single_iteam\"><img src=\"images/550x330x4.jpg\" alt=\"\">\r\n                <h2><a class=\"slider_tittle\" href=\"pages/single.html\">Fusce eu nulla semper porttitor felis sit amet</a></h2>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </div>\r\n        <div class=\"col-lg-6 col-md-6 col-sm6\">\r\n          <div class=\"content_top_right\">\r\n            <ul class=\"featured_nav wow fadeInDown\">\r\n              <li><img src=\"images/300x215x1.jpg\" alt=\"\">\r\n                <div class=\"title_caption\"><a href=\"pages/single.html\">Sed luctus semper odio aliquam rhoncus</a></div>\r\n              </li>\r\n              <li><img src=\"images/300x215x2.jpg\" alt=\"\">\r\n                <div class=\"title_caption\"><a href=\"pages/single.html\">Sed luctus semper odio aliquam rhoncus</a></div>\r\n");
      out.write("              </li>\r\n              <li><img src=\"images/300x215x3.jpg\" alt=\"\">\r\n                <div class=\"title_caption\"><a href=\"pages/single.html\">Sed luctus semper odio aliquam rhoncus</a></div>\r\n              </li>\r\n              <li><img src=\"images/300x215x4.jpg\" alt=\"\">\r\n                <div class=\"title_caption\"><a href=\"pages/single.html\">Sed luctus semper odio aliquam rhoncus</a></div>\r\n              </li>\r\n            </ul>\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </div> -->\r\n    <div class=\"content_middle\">\r\n      <div class=\"col-lg-3 col-md-3 col-sm-3\">\r\n        <div class=\"content_middle_leftbar\">\r\n          <div class=\"single_category wow fadeInDown\">\r\n            <h2> <span class=\"bold_line\"><span></span></span> <span class=\"solid_line\"></span> <a href=\"#\" class=\"title_text\">Sức khoẻ</a> </h2>\r\n            <ul class=\"catg1_nav\">\r\n              <li>\r\n                <div class=\"catgimg_container\"> <a href=\"pages/single.html\" class=\"catg1_img\"><img alt=\"\" src=\"images/Mai-Phuong-xuat-vien.jpg\"></a></div>\r\n");
      out.write("                <h3 class=\"post_titile\"><a href=\"pages/single.html\">Diễn viên Mai Phương khập khiễng xuất viện</a></h3>\r\n              </li>\r\n              <li>\r\n                <div class=\"catgimg_container\"> <a href=\"pages/single.html\" class=\"catg1_img\"><img alt=\"\" src=\"images/BENH-VIEN-VL-2018.jpg\"></a></div>\r\n                <h3 class=\"post_titile\"><a href=\"pages/single.html\">Bác sĩ sai sót trong vụ thiếu úy cảnh sát tử vong do uống nhầm ma túy</a></h3>\r\n              </li>\r\n            </ul>\r\n          </div>\r\n        </div>\r\n      </div>\r\n      <div class=\"col-lg-6 col-md-6 col-sm-6\">\r\n        <div class=\"content_middle_middle\">\r\n          <div class=\"slick_slider2\">\r\n            <div class=\"single_featured_slide\">\r\n              <a href=\"pages/single.html\"><img src=\"images/xalattop.jpg\" alt=\"\"></a>\r\n              <h2><a href=\"pages/single.html\">Đường 5.000 tỷ nối bốn quận, huyện Hà Nội sắp khánh thành</a></h2>\r\n              <p>Hơn 20 km đường trục Nam Hà Nội với tổng mức đầu tư 5.000 tỷ đồng đã được thảm nhựa, trồng cây xanh để khánh thành dịp 10/10.</p>\r\n");
      out.write("            </div>\r\n            <div class=\"single_featured_slide\"> <a href=\"pages/single.html\"><img src=\"images/rung-thong.jpg\" alt=\"\"></a>\r\n              <h2><a href=\"#\">Khu rừng thông ba lá ở Lâm Đồng bị đầu độc</a></h2>\r\n              <p>Đám rừng thông ba lá ở huyện Bảo Lâm đang héo lá, chết dần khi bị đầu độc bằng thuốc diệt cỏ.</p>\r\n            </div>\r\n            <div class=\"single_featured_slide\"> <a href=\"pages/single.html\"><img src=\"images/x-trail-14.jpg\" alt=\"\"></a>\r\n              <h2><a href=\"#\">Nissan X-Trail mới giá từ 991 triệu tại Việt Nam</a></h2>\r\n              <p>Crossover 5+2 nâng cấp một số tính năng, thay đổi nhẹ ở ngoại thất trên phiên bản V-series, dành riêng cho thị trường Việt Nam.</p>\r\n            </div>\r\n          </div>\r\n        </div>\r\n      </div>\r\n      <div class=\"col-lg-3 col-md-3 col-sm-3\">\r\n        <div class=\"content_middle_rightbar\">\r\n          <div class=\"single_category wow fadeInDown\">\r\n            <h2> <span class=\"bold_line\"><span></span></span> <span class=\"solid_line\"></span> <a href=\"#\" class=\"title_text\">Giải trí</a> </h2>\r\n");
      out.write("            <ul class=\"catg1_nav\">\r\n              <li>\r\n                <div class=\"catgimg_container\"> <a href=\"pages/single.html\" class=\"catg1_img\"><img alt=\"\" src=\"images/sui-he-14.jpg\"></a></div>\r\n                <h3 class=\"post_titile\"><a href=\"pages/single.html\">Hà Tuệ - nàng thơ phương Đông của show nội y Victoria’s Secret</a></h3>\r\n              </li>\r\n              <li>\r\n                <div class=\"catgimg_container\"> <a href=\"pages/single.html\" class=\"catg1_img\"><img alt=\"\" src=\"images/phung-ngoc-huy.jpg\"></a></div>\r\n                <h3 class=\"post_titile\"><a href=\"pages/single.html\">Bạn trai cũ hát quyên góp giúp Mai Phương trị ung thư</a></h3>\r\n              </li>\r\n            </ul>\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </div>\r\n    <div class=\"content_bottom\">\r\n      <div class=\"col-lg-8 col-md-8\">\r\n        <div class=\"content_bottom_left\">\r\n          <div class=\"single_category wow fadeInDown\">\r\n            <h2> <span class=\"bold_line\"><span></span></span> <span class=\"solid_line\"></span> <a class=\"title_text\" href=\"#\">Kinh tế</a> </h2>\r\n");
      out.write("            <div class=\"business_category_left wow fadeInDown\">\r\n              <ul class=\"fashion_catgnav\">\r\n                <li>\r\n                  <div class=\"catgimg2_container\"> <a href=\"pages/single.html\"><img alt=\"\" src=\"images/saigon-tower-1-8289-1536576583.jpg\"></a> </div>\r\n                  <h2 class=\"catg_titile\"><a href=\"pages/single.html\">Ngân hàng ồ ạt rao bán tài sản nghìn tỷ thu hồi nợ</a></h2>\r\n                  <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                  <p>Có ngân hàng chỉ trong thời gian ngắn rao bán tài sản có giá trị lên đến hàng chục nghìn tỷ đồng.</p>\r\n                </li>\r\n              </ul>\r\n            </div>\r\n            <div class=\"business_category_right wow fadeInDown\">\r\n              <ul class=\"small_catg\">\r\n                <li>\r\n                  <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"pages/single.html\"><img src=\"images/jack-ma-daniel-zhang-5686-1536548678.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"media-body\">\r\n                      <h4 class=\"media-heading\"><a href=\"pages/single.html\">Tâm thư ấn định ngày nghỉ hưu của Jack Ma</a></h4>\r\n                      <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                    </div>\r\n                  </div>\r\n                </li>\r\n                <li>\r\n                  <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"pages/single.html\"><img src=\"images/jack-ma-daniel-zhang-5686-1536548678.jpg\" alt=\"\"></a>\r\n                    <div class=\"media-body\">\r\n                      <h4 class=\"media-heading\"><a href=\"pages/single.html\">Tâm thư ấn định ngày nghỉ hưu của Jack Ma</a></h4>\r\n                      <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n");
      out.write("                    </div>\r\n                  </div>\r\n                </li>\r\n                <li>\r\n                  <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/toan-canh-dien-dan-kinh-te-the-gioi-ve-asean-sap-dien-ra-o-ha-noi-1536549560_180x108.jpg\" alt=\"\"></a>\r\n                    <div class=\"media-body\">\r\n                      <h4 class=\"media-heading\"><a href=\"#\">Toàn cảnh Diễn đàn Kinh tế thế giới về ASEAN sắp diễn ra ở Hà Nội</a></h4>\r\n                      <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                    </div>\r\n                  </div>\r\n                </li>\r\n                <li>\r\n                  <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/hm1-5523-1536315033.jpg\" alt=\"\"></a>\r\n                    <div class=\"media-body\">\r\n                      <h4 class=\"media-heading\"><a href=\"#\">'Cá mập' thời trang thế giới đổ về Việt Nam</a></h4>\r\n");
      out.write("                      <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                    </div>\r\n                  </div>\r\n                </li>\r\n              </ul>\r\n            </div>\r\n          </div>\r\n          <div class=\"games_fashion_area\">\r\n            <div class=\"games_category\">\r\n              <div class=\"single_category\">\r\n                <h2> <span class=\"bold_line\"><span></span></span> <span class=\"solid_line\"></span> <a class=\"title_text\" href=\"#\">Du lịch</a> </h2>\r\n                <ul class=\"fashion_catgnav wow fadeInDown\">\r\n                  <li>\r\n                    <div class=\"catgimg2_container\"> <a href=\"pages/single.html\"><img alt=\"\" src=\"images/1-1536309215_680x0.jpg\"></a> </div>\r\n                    <h2 class=\"catg_titile\"><a href=\"#\">10 thành phố có mùa thu đẹp ở châu Âu</a></h2>\r\n                    <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n");
      out.write("                    <p>Những ngày tháng 9-10 là dịp lý tưởng để tận hưởng khí trời mát mẻ, khung cảnh rực rỡ sắc lá vàng ở Anh, Italy...</p>\r\n                  </li>\r\n                </ul>\r\n                <ul class=\"small_catg wow fadeInDown\">\r\n                  <li>\r\n                    <div class=\"media\"> <a class=\"media-left\" href=\"#\"><img src=\"images/binhgom-14_180x108.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Ngôi chùa ở Sài Gòn có nhiều bình gốm nhất Việt Nam</a></h4>\r\n                        <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                      </div>\r\n                    </div>\r\n                  </li>\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/dulich149552332892871495523728-8608-5967-1536491676_180x108.jpg\" alt=\"\"></a>\r\n");
      out.write("                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Vì sao ngày càng có nhiều người bỏ việc đi du lịch?</a></h4>\r\n                        <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                      </div>\r\n                    </div>\r\n                  </li>\r\n                </ul>\r\n              </div>\r\n            </div>\r\n            <div class=\"fashion_category\">\r\n              <div class=\"single_category\">\r\n                <div class=\"single_category wow fadeInDown\">\r\n                  <h2> <span class=\"bold_line\"><span></span></span> <span class=\"solid_line\"></span> <a class=\"title_text\" href=\"#\">Thể thao</a> </h2>\r\n                  <ul class=\"fashion_catgnav wow fadeInDown\">\r\n                    <li>\r\n                      <div class=\"catgimg2_container\"> <a href=\"#\"><img alt=\"\" src=\"images/mo2-2406-1536586916.jpg\"></a> </div>\r\n");
      out.write("                      <h2 class=\"catg_titile\"><a href=\"#\">Tin Thể thao tối 10/9: Ramos ca ngợi Modric, 'đá xoáy' Ronaldo</a></h2>\r\n                      <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                      <p>Ramos khen Modric xứng đáng thắng giải Cầu thủ hay nhất UEFA, danh hiệu mà Cristiano Ronaldo chỉ về thứ hai.</p>\r\n                    </li>\r\n                  </ul>\r\n                  <ul class=\"small_catg wow fadeInDown\">\r\n                    <li>\r\n                      <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/zinedinezidane-cropped-hca02r3-9291-6203-1536554003.jpg\" alt=\"\"></a>\r\n                        <div class=\"media-body\">\r\n                          <h4 class=\"media-heading\"><a href=\"#\">Zidane: 'Tôi sẽ sớm trở lại bóng đá'</a></h4>\r\n                          <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n");
      out.write("                        </div>\r\n                      </div>\r\n                    </li>\r\n                    <li>\r\n                      <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/Nole-3417-1536567122.jpg\" alt=\"\"></a>\r\n                        <div class=\"media-body\">\r\n                          <h4 class=\"media-heading\"><a href=\"#\">Djokovic: 'Federer và Nadal đã thúc đẩy tôi'</a></h4>\r\n                          <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                        </div>\r\n                      </div>\r\n                    </li>\r\n                  </ul>\r\n                </div>\r\n              </div>\r\n            </div>\r\n          </div>\r\n          <div class=\"technology_catrarea\">\r\n            <div class=\"single_category\">\r\n              <h2> <span class=\"bold_line\"><span></span></span> <span class=\"solid_line\"></span> <a class=\"title_text\" href=\"#\">Khoa học</a> </h2>\r\n");
      out.write("              <div class=\"business_category_left\">\r\n                <ul class=\"fashion_catgnav wow fadeInDown\">\r\n                  <li>\r\n                    <div class=\"catgimg2_container\"> <a href=\"#\"><img alt=\"\" src=\"images/VNEAITop-1536557196-5742-1536557443_180x108.jpg\"></a> </div>\r\n                    <h2 class=\"catg_titile\"><a href=\"#\">Trí tuệ nhân tạo làm thay đổi mọi mặt đời sống con người</a></h2>\r\n                    <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                    <p>Trí tuệ nhân tạo đang hiện hữu trong mọi lĩnh vực đời sống, giúp con người tiết kiệm sức lao động đồng thời nâng cao hiệu quả công việc. </p>\r\n                  </li>\r\n                </ul>\r\n              </div>\r\n              <div class=\"business_category_right\">\r\n                <ul class=\"small_catg wow fadeInDown\">\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/cong-nghe-tren-xe-tu-lai-phuong-tien-tuong-lai-cua-con-nguoi-1536547432_180x108.jpg\" alt=\"\"></a>\r\n");
      out.write("                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Công nghệ trên xe tự lái - phương tiện di chuyển của tương lai</a></h4>\r\n                        <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                      </div>\r\n                    </div>\r\n                  </li>\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/cong-nghe-tren-xe-tu-lai-phuong-tien-tuong-lai-cua-con-nguoi-1536547432_180x108.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Công nghệ trên xe tự lái - phương tiện di chuyển của tương lai</a></h4>\r\n                        <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n");
      out.write("                      </div>\r\n                    </div>\r\n                  </li>\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/sieu-vat-lieu-4963-1536510002.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Người Việt sáng chế siêu vật liệu hấp thụ sóng điện từ</a></h4>\r\n                        <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                      </div>\r\n                    </div>\r\n                  </li>\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/HoanangluongMTset-1536381504-9774-1536381579_180x108.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Thiết bị năng lượng hình hoa tự động quay theo mặt trời</a></h4>\r\n");
      out.write("                        <div class=\"comments_box\"> <span class=\"meta_date\">10/09/2018</span> <span class=\"meta_comment\"><a href=\"#\">Nguồn: vnexpress</a></span> <span class=\"meta_more\"><a  href=\"#\">Chi tiết...</a></span> </div>\r\n                      </div>\r\n                    </div>\r\n                  </li>\r\n                </ul>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </div>\r\n      </div>\r\n      <div class=\"col-lg-4 col-md-4\">\r\n        <div class=\"content_bottom_right\">\r\n          <div class=\"single_bottom_rightbar\">\r\n            <h2>Start up</h2>\r\n            <ul class=\"small_catg popular_catg wow fadeInDown\">\r\n              <li>\r\n                <div class=\"media wow fadeInDown\"> <a href=\"#\" class=\"media-left\"><img alt=\"\" src=\"images/PR-898x505-8224-1536118087.jpg\"> </a>\r\n                  <div class=\"media-body\">\r\n                    <h4 class=\"media-heading\"><a href=\"#\">Bốn bước quan hệ công chúng giúp startup thu hút đầu tư</a></h4>\r\n                    <p>Chuyên gia cho biết một quy trình quan hệ công chúng (PR) 4 bước gồm \"Xác định- Truyền thông- Khẳng định- Thu hút\" sẽ giúp doanh nghiệp thu hút vốn.</p>\r\n");
      out.write("                  </div>\r\n                </div>\r\n              </li>\r\n              <li>\r\n                <div class=\"media wow fadeInDown\"> <a href=\"#\" class=\"media-left\"><img alt=\"\" src=\"images/anh1-jpeg-7118-1536141729-5632-1536197161.jpg\"> </a>\r\n                  <div class=\"media-body\">\r\n                    <h4 class=\"media-heading\"><a href=\"#\">CEO 16 tuổi làm giàu từ thương mại điện tử</a></h4>\r\n                    <p>Sở hữu năm website bán hàng trực tuyến, Giám đốc điều hành 16 tuổi cho biết công thức thành công là đam mê và kỹ năng quản lý thời gian.</p>\r\n                  </div>\r\n                </div>\r\n              </li>\r\n              <li>\r\n                <div class=\"media wow fadeInDown\"> <a href=\"#\" class=\"media-left\"><img alt=\"\" src=\"images/meetup-2904-1536142216.jpg\"> </a>\r\n                  <div class=\"media-body\">\r\n                    <h4 class=\"media-heading\"><a href=\"#\">Startup Việt 2018 mở đăng ký cho cộng đồng khởi nghiệp</a></h4>\r\n                    <p>Từ ngày 5/9, các startup trong nước có thể nộp hồ sơ trực tuyến, tham gia sự kiện khởi nghiệp Startup Việt 2018 trên website chính thức của chương trình. </p>\r\n");
      out.write("                  </div>\r\n                </div>\r\n              </li>\r\n            </ul>\r\n          </div>\r\n          <div class=\"single_bottom_rightbar\">\r\n            <ul role=\"tablist\" class=\"nav nav-tabs custom-tabs\">\r\n              <li class=\"active\" role=\"presentation\"><a data-toggle=\"tab\" role=\"tab\" aria-controls=\"home\" href=\"#mostPopular\">Bài báo hot nhất</a></li>\r\n              <li role=\"presentation\"><a data-toggle=\"tab\" role=\"tab\" aria-controls=\"messages\" href=\"#recentComent\">Bài viết vừa đọc</a></li>\r\n            </ul>\r\n            <div class=\"tab-content\">\r\n              <div id=\"mostPopular\" class=\"tab-pane fade in active\" role=\"tabpanel\">\r\n                <ul class=\"small_catg popular_catg wow fadeInDown\">\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/rick-kid.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Người giàu Việt ngày càng nhiều, chi tiêu càng cao</a></h4>\r\n");
      out.write("                        <p>Những món hàng giá \"đắt vô lý\" với không ít người, dần được đón nhận nhiều hơn ở Việt Nam nhờ giới nhà giàu và siêu giàu.</p>\r\n                      </div>\r\n                    </div>\r\n                  </li>\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/hdba-3799-1524283352-8325-1536585488.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Ngân hàng Nhà nước chấp thuận sáp nhập PGBank vào HDBank</a></h4>\r\n                        <p>Dự kiến cuối năm nay thương vụ sáp nhập PGBank và HDBank sẽ hoàn tất và ngân hàng sau sáp nhập có quy mô vốn điều lệ 15.345 tỷ đồng.</p>\r\n                      </div>\r\n                    </div>\r\n                  </li>\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/cacbicao-9214-1536578814.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n");
      out.write("                        <h4 class=\"media-heading\"><a href=\"#\">Cựu cán bộ Công an TP HCM lĩnh 14 năm tù vì buôn lậu 54 ôtô sang</a></h4>\r\n                        <p>Lam và đồng phạm thuê Việt kiều mang xe Rolls Royce, Bentley, Lexus, Porsche... về Sài Gòn bán cho chủ salon ôtô thu lợi hàng chục tỷ.</p>\r\n                      </div>\r\n                    </div>\r\n                  </li>\r\n                </ul>\r\n              </div>\r\n              <div id=\"recentComent\" class=\"tab-pane fade\" role=\"tabpanel\">\r\n                <ul class=\"small_catg popular_catg\">\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/112x112.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Duis condimentum nunc pretium lobortis </a></h4>\r\n                        <p>Nunc tincidunt, elit non cursus euismod, lacus augue ornare metus, egestas imperdiet nulla nisl quis mauris. Suspendisse a pharetra </p>\r\n");
      out.write("                      </div>\r\n                    </div>\r\n                  </li>\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/112x112.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Duis condimentum nunc pretium lobortis </a></h4>\r\n                        <p>Nunc tincidunt, elit non cursus euismod, lacus augue ornare metus, egestas imperdiet nulla nisl quis mauris. Suspendisse a pharetra </p>\r\n                      </div>\r\n                    </div>\r\n                  </li>\r\n                  <li>\r\n                    <div class=\"media wow fadeInDown\"> <a class=\"media-left\" href=\"#\"><img src=\"images/112x112.jpg\" alt=\"\"></a>\r\n                      <div class=\"media-body\">\r\n                        <h4 class=\"media-heading\"><a href=\"#\">Duis condimentum nunc pretium lobortis </a></h4>\r\n                        <p>Nunc tincidunt, elit non cursus euismod, lacus augue ornare metus, egestas imperdiet nulla nisl quis mauris. Suspendisse a pharetra </p>\r\n");
      out.write("                      </div>\r\n                    </div>\r\n                  </li>\r\n                </ul>\r\n              </div>\r\n            </div>\r\n          </div>\r\n          <div class=\"single_bottom_rightbar wow fadeInDown\">\r\n              <h2>Thẻ gán</h2>\r\n              <ul class=\"labels_nav\">\r\n                <li><a href=\"#\">Giải trí</a></li>\r\n                <li><a href=\"#\">Sức khoẻ</a></li>\r\n                <li><a href=\"#\">Thời sự</a></li>\r\n                <li><a href=\"#\">Thời trang</a></li>\r\n                <li><a href=\"#\">Thể thao</a></li>\r\n                <li><a href=\"#\">Công nghệ số</a></li>\r\n                <li><a href=\"#\">Kinh tế</a></li>\r\n                <li><a href=\"#\">Start up</a></li>\r\n              </ul>\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </div>\r\n  </section>\r\n</div>\r\n<footer id=\"footer\">\r\n  <div class=\"footer_top\">\r\n    <div class=\"container\">\r\n      <div class=\"row\">\r\n        <div class=\"col-lg-4 col-md-4 col-sm-4\">\r\n          <div class=\"single_footer_top wow fadeInRight\">\r\n");
      out.write("            <h2>Giới thiệu</h2>\r\n            <p><strong>Thành lập ngày 10/09/2018.</strong><br>\r\n            <strong>Nhóm sinh viên trường đại học Công nghiệp Hà Nội</strong>.<br>\r\n            <!-- <strong>Giấy phép:</strong> XXX.<br> -->\r\n            <strong>Điện thoại:</strong> 033-4492-484<br>\r\n            <strong>Người thực hiện:</strong><br>\r\n            <span style=\"margin-left: 20px;\">- Nguyễn Như Thuỳ</span><br>\r\n            <span style=\"margin-left: 20px;\">- Nguyễn Trung Hiếu</span><br>\r\n            <span style=\"margin-left: 20px;\">- Trần Quang Minh</span><br>\r\n            </p>\r\n            <p>\r\n            <!-- <strong>Tòa soạn:</strong> XXX. -->\r\n            <!-- <strong>Đường dây nóng:</strong> 0123 123 0123<br> -->\r\n            <!-- <strong>Fax:</strong> 024 3795 XXXX -->\r\n            </p>\r\n          </div>\r\n        </div>\r\n        <div class=\"col-lg-4 col-md-4 col-sm-4\">\r\n            <div class=\"single_footer_top wow fadeInRight\">\r\n              <a href=\"index.html\"><img src=\"images/favorite-icon.png\" height=\"150px\"></a>\r\n");
      out.write("            </div>\r\n          </div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n  <div class=\"footer_bottom\">\r\n    <div class=\"container\">\r\n      <div class=\"row\">\r\n        <div class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\">\r\n          <div class=\"footer_bottom_left\">\r\n            <p>Copyright &copy; 2018 <a href=\"index.html\">magExpress</a></p>\r\n          </div>\r\n        </div>\r\n        <div class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\">\r\n          <div class=\"footer_bottom_right\">\r\n            <p>Developed BY Wpfreeware</p>\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</footer>\r\n\r\n<!-- Modal Sign in-->\r\n<div class=\"modal fade\" id=\"modalSignIn\" role=\"dialog\">\r\n  <div class=\"modal-dialog modal-md\">\r\n    <div class=\"modal-content\">\r\n      <form action=\"#\" class=\"search_form\">\r\n        <div class=\"modal-body\">\r\n          <div class=\"form-group\">\r\n            <label for=\"usr\">Tên đăng nhập:</label>\r\n            <input type=\"email\" class=\"form-control\" id=\"usr\" placeholder=\"Email\">\r\n          </div>\r\n");
      out.write("          <div class=\"form-group\">\r\n            <label for=\"pwd\">Mật khẩu:</label>\r\n            <input type=\"password\" class=\"form-control\" id=\"pwd\" placeholder=\"Mật khẩu\">\r\n          </div>\r\n        </div>\r\n        <div class=\"modal-footer\">\r\n          <a href=\"#\">Quên mật khẩu?</a>\r\n          <button type=\"submit\" class=\"btn btn-default modal-submit\" data-dismiss=\"modal\">Đăng nhập</button>\r\n          <br>\r\n          <div class=\"share_post\">\r\n            <a class=\"facebook\" href=\"#\"><i class=\"fa fa-facebook\"></i>Facebook</a>\r\n            <a class=\"twitter\" href=\"#\"><i class=\"fa fa-twitter\"></i>Twitter</a>\r\n            <a class=\"googleplus\" href=\"#\"><i class=\"fa fa-google-plus\"></i>Google+</a>\r\n            <a class=\"linkedin\" href=\"#\"><i class=\"fa fa-linkedin\"></i>LinkedIn</a>\r\n            <a class=\"pinterest\" href=\"#\"><i class=\"fa fa-pinterest\"></i>Pinterest</a>\r\n            <a class=\"stumbleupon\" href=\"#\"><i class=\"fa fa-stumbleupon\"></i>StumbleUpon</a>\r\n          </div>\r\n        </div>\r\n      </form>\r\n    </div>\r\n");
      out.write("  </div>\r\n</div>\r\n\r\n<!-- Modal Sign up-->\r\n<div class=\"modal fade\" id=\"modalSignUp\" role=\"dialog\">\r\n    <div class=\"modal-dialog modal-md\">\r\n      <div class=\"modal-content\">\r\n        <form action=\"#\" class=\"search_form\">\r\n          <div class=\"modal-body\">\r\n            <div class=\"form-group\">\r\n              <label for=\"usr\">Tên đăng nhập:</label>\r\n              <input type=\"email\" class=\"form-control\" id=\"usr\" placeholder=\"Email\">\r\n            </div>\r\n            <div class=\"form-group\">\r\n              <label for=\"pwd\">Mật khẩu:</label>\r\n              <input type=\"password\" class=\"form-control\" id=\"pwd\" placeholder=\"Mật khẩu\">\r\n            </div>\r\n          </div>\r\n          <div class=\"modal-footer\">\r\n            <button type=\"submit\" class=\"btn btn-default modal-submit\" data-dismiss=\"modal\">Đăng ký</button>\r\n            <br>\r\n            <div class=\"share_post\">\r\n              <a class=\"facebook\" href=\"#\"><i class=\"fa fa-facebook\"></i>Facebook</a>\r\n              <a class=\"twitter\" href=\"#\"><i class=\"fa fa-twitter\"></i>Twitter</a>\r\n");
      out.write("              <a class=\"googleplus\" href=\"#\"><i class=\"fa fa-google-plus\"></i>Google+</a>\r\n              <a class=\"linkedin\" href=\"#\"><i class=\"fa fa-linkedin\"></i>LinkedIn</a>\r\n              <a class=\"pinterest\" href=\"#\"><i class=\"fa fa-pinterest\"></i>Pinterest</a>\r\n              <a class=\"stumbleupon\" href=\"#\"><i class=\"fa fa-stumbleupon\"></i>StumbleUpon</a>\r\n            </div>\r\n          </div>\r\n        </form>\r\n      </div>\r\n    </div>\r\n  </div>\r\n<script src=\"assets/js/jquery.min.js\"></script>\r\n<script src=\"assets/js/bootstrap.min.js\"></script>\r\n<script src=\"assets/js/wow.min.js\"></script>\r\n<script src=\"assets/js/slick.min.js\"></script>\r\n<script src=\"assets/js/custom.js\"></script>\r\n</body>\r\n</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
